{
  "formatVersion": "1.1",
  "component": {
    "group": "com.asm.plugin",
    "module": "time",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "time-1.0.0.jar",
          "url": "time-1.0.0.jar",
          "size": 29995,
          "sha512": "729b6461d4af7f23bedc5a20a0c09eb52a6887a8dd255abfaa4b96ad15c9cee8657f13b33dedf31f643c88c596877f92f56fd435d2b24b32ab2ac32f8c50ad22",
          "sha256": "bfaa4c5ac91267d0cb0f0931b3c3f2d19454cca8caea45d89927f7d16d0df3f8",
          "sha1": "bb0fa95fdc6c3295bc5cf819542e35d7658bd31a",
          "md5": "b83c595e8b5053a5a7b47bc9c33f11f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "6.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "6.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "time-1.0.0.jar",
          "url": "time-1.0.0.jar",
          "size": 29995,
          "sha512": "729b6461d4af7f23bedc5a20a0c09eb52a6887a8dd255abfaa4b96ad15c9cee8657f13b33dedf31f643c88c596877f92f56fd435d2b24b32ab2ac32f8c50ad22",
          "sha256": "bfaa4c5ac91267d0cb0f0931b3c3f2d19454cca8caea45d89927f7d16d0df3f8",
          "sha1": "bb0fa95fdc6c3295bc5cf819542e35d7658bd31a",
          "md5": "b83c595e8b5053a5a7b47bc9c33f11f9"
        }
      ]
    }
  ]
}
